### PR TITLE
Fixes for intentional line breaks and newlines between comments

### LINKED ISSUE #59: mix formats removes intentional single blanks
Running `mix format` removes some spaces, that should stay in place in heex templates:
```diff
-    Last <%= length(@backlog_feeds) %> of <%= @feedcount %> backlog feeds
+    Last<%= length(@backlog_feeds) %>of<%= @feedcount %>backlog feeds
```
In case you want to see more context, the file, I ran mix format on is [over here](https://github.com/PanoptikumIO/pan/blob/main/lib/pan_web/templates/feed_backlog/index.html.heex#L24).
Happy to provide more information, basically all versions used are [current](https://github.com/PanoptikumIO/pan/blob/main/mix.lock).

Cheers, and happy to see this project making progress! The last changes fixed lots of issues I had with the formatter! :heart_eyes:

### LINKED ISSUE #60: additional new lines above and below HTML comment tags every time formatter is run
This code grows in new lines above and below the comment when it contains an eex block

Before:
```html
<div></div>
<!-- <%= "comment" %> -->
<div></div>
```

After running formatter twice:
```html
<div></div>


<!-- <%= "comment" %> -->


<div></div>
```

### PR DESCRIPTION
**Pull request by feliperenan**
Fixes https://github.com/feliperenan/heex_formatter/issues/59 and Fixes https://github.com/feliperenan/heex_formatter/issues/60

### CODE REVIEW

File: lib/heex_formatter/algebra.ex [hunk 1]
```diff
@@ -218,16 +211,21 @@ defmodule HeexFormatter.Algebra do
...
-    else
-      {:inline,
-       text
-       |> String.split(["\r\n", "\n"])
-       |> Enum.map(&String.trim/1)
-       |> Enum.drop_while(&(&1 == ""))
-       |> text_to_algebra(0, [])}
+  defp to_algebra({:text, text, _meta}, _context) when is_binary(text) do
+    cond do
+      only_spaces?(text) ->
```
Comment (feliperenan) [inline lib/heex_formatter/algebra.ex]: This handle this case here:

```
<%= @user.first_name %> <%= @user.last_name %>
```

before this code, it would break line between them.

File: .credo.exs [hunk 2]
```diff
@@ -121,7 +121,7 @@
           #
           {Credo.Check.Refactor.Apply, []},
           {Credo.Check.Refactor.CondStatements, []},
-          {Credo.Check.Refactor.CyclomaticComplexity, []},
+          {Credo.Check.Refactor.CyclomaticComplexity, [max_complexity: 16]},
```
Comment (feliperenan) [inline .credo.exs:124]: 🙈

File: lib/heex_formatter.ex [hunk 3]
```diff
@@ -327,8 +327,13 @@ defmodule HeexFormatter do
   defp to_tree([{:text, text, %{context: [:comment_end]}} | tokens], buffer, [
          {:comment, start_text, upper_buffer} | stack
        ]) do
-    comment_block = {:comment_block, start_text, Enum.reverse([{:text, text, %{}} | buffer])}
-    to_tree(tokens, [comment_block | upper_buffer], stack)
+    buffer = Enum.reverse([{:text, String.trim_trailing(text), %{}} | buffer])
+
+    to_tree(
+      tokens,
+      [{:comment_block, String.trim_leading(start_text), buffer} | upper_buffer],
```
Comment (feliperenan) [inline lib/heex_formatter.ex]: Trimming the strings here solves this issue: https://github.com/feliperenan/heex_formatter/issues/60 🙌🏻

File: lib/heex_formatter.ex [hunk 4]
```diff
@@ -327,8 +327,13 @@ defmodule HeexFormatter do
   defp to_tree([{:text, text, %{context: [:comment_end]}} | tokens], buffer, [
          {:comment, start_text, upper_buffer} | stack
        ]) do
```
Comment (josevalim) [inline lib/heex_formatter.ex:329]:
```suggestion
  defp to_tree(
         [{:text, text, %{context: [:comment_end]}} | tokens],
         buffer,
         [{:comment, start_text, upper_buffer} | stack]
       ) do
```

File: lib/heex_formatter/algebra.ex [hunk 5]
```diff
@@ -52,45 +30,61 @@ defmodule HeexFormatter.Algebra do
...
         |> to_algebra(context)
         |> maybe_force_unfit()
 
       cond do
         prev_type == :inline and next_type == :inline ->
-          {next_type, concat([prev_doc, flex_break(""), next_doc])}
+          on_break =
+            if next_doc != empty() and
+                 context.mode !== :script and
+                 context.mode !== :comment and
```
Comment (josevalim) [inline lib/heex_formatter/algebra.ex]: Do we want to add a space during `pre`? We probably don't want to do that either... so maybe this should be:

```suggestion
                 context.mode == :normal
```

File: lib/heex_formatter/algebra.ex (hunk 1 above)
Comment (josevalim) [reply lib/heex_formatter/algebra.ex]: Instead of both `only_spaces?` and `String.trim_leading`, you could have a function called: `classify_leading(string)`.

It returns three possible atoms: `:spaces`, `:newline`, `:other`. Then you can transform this `cond` into a `case` and traverse the text only once. :)

File: lib/heex_formatter.ex (hunk 3 above)
Comment (josevalim) [reply lib/heex_formatter.ex]: Nice! I think btw this could be written like this:

```suggestion
      [{:comment_block, [{:text, String.trim_leading(start_text), %{}} | buffer]} | upper_buffer],
```

There is no reason to treat start differently. :)

File: lib/heex_formatter.ex [hunk 6]
```diff
@@ -327,8 +327,13 @@ defmodule HeexFormatter do
...
-    comment_block = {:comment_block, start_text, Enum.reverse([{:text, text, %{}} | buffer])}
-    to_tree(tokens, [comment_block | upper_buffer], stack)
+    buffer = Enum.reverse([{:text, String.trim_trailing(text), %{}} | buffer])
+
+    to_tree(
+      tokens,
+      [{:comment_block, [{:text, String.trim_leading(start_text), %{}} | buffer]} | upper_buffer],
```
Comment (josevalim) [inline lib/heex_formatter.ex]: Maybe we should also rename this node to :html_comment as we will add :eex_comment in the future!
